version: "3.7"
services:
  app:
    build:
      args:
        user: prog
        uid: 1000
      context: ./
      dockerfile: DockerFile
    image: niagahoster_laravel
    container_name: niagahoster_laravel
    restart: unless-stopped
    working_dir: /var/www/niagahoster_laravel
    volumes:
      - ./niagahoster_laravel:/var/www/niagahoster_laravel
    networks:
      - niagahoster

  db:
    image: postgres:14.4-alpine
    container_name: niagahoster_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - niagahoster

  nginx:
    image: nginx:alpine
    container_name: niagahoster_nginx
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./niagahoster.conf:/etc/nginx/conf.d/default.conf
      - ./niagahoster.conf:/etc/nginx/conf.d/default
      - ./niagahoster.conf:/etc/nginx/sites-enable/default
      - ./niagahoster.conf:/etc/nginx/sites-enable/default.conf
    networks:
      - niagahoster

networks:
  niagahoster:
    driver: bridge
